---
# Source: wordpress/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: blog-mariadb
  labels:
    app: blog-mariadb
    chart: "mariadb-2.1.1"
    release: "blog"
    heritage: "Tiller"
type: Opaque
data:
  mariadb-root-password: "Yml0bmFtaQ=="
  mariadb-password: "Yml0bmFtaQ=="
