# Source: wordpress/charts/mariadb/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: blog-mariadb
  labels:
    app: blog-mariadb
    chart: "mariadb-2.1.1"
    release: "blog"
    heritage: "Tiller"
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: blog-mariadb
