# Source: wordpress/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: blog-wordpress
  labels:
    app: blog-wordpress
    chart: "wordpress-1.0.5"
    release: "blog"
    heritage: "Tiller"
type: Opaque
data:

  wordpress-password: "Yml0bmFtaQ=="

  smtp-password: ""
