# Source: wordpress/templates/pvc.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blog-wordpress
  labels:
    app: blog-wordpress
    chart: "wordpress-1.0.5"
    release: "blog"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
