# Source: wordpress/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: blog-wordpress
  labels:
    app: blog-wordpress
    chart: "wordpress-1.0.5"
    release: "blog"
    heritage: "Tiller"
spec:
  type: NodePort
  externalTrafficPolicy: "Local"
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: blog-wordpress
