apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: exercise-01
spec:
  type: NodePort
  ports:
  - name: wordpressport
    port: 80
    targetPort: wordpressport
  selector:
    app: wordpress