apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: exercise-01
spec:
  type: ClusterIP
  ports:
  - name: mariadbport
    port: 3306
    targetPort: mariadbport
  selector:
    app: mariadb